apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: cipher-ai
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=        # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM=   #  password base64
  POSTGRES_DB: Y2lwaGVyX2Fp          # cipher_ai
